# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/sink/sink.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'v1/sink/sink.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12v1/sink/sink.proto\x12\x0b\x61pi.v1.sink\x1a\x19google/protobuf/any.proto\"-\n\rDoSinkRequest\x12\x0e\n\x06sinkId\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x08\x32J\n\x07\x44\x61taHub\x12?\n\x06\x44oSink\x12\x1a.api.v1.sink.DoSinkRequest\x1a\x15.api.v1.sink.Response\"\x00(\x01\x42-Z+github.com/tomeai/dataflow/api/v1/sink;sinkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.sink.sink_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/tomeai/dataflow/api/v1/sink;sink'
  _globals['_DOSINKREQUEST']._serialized_start=62
  _globals['_DOSINKREQUEST']._serialized_end=107
  _globals['_RESPONSE']._serialized_start=109
  _globals['_RESPONSE']._serialized_end=135
  _globals['_DATAHUB']._serialized_start=137
  _globals['_DATAHUB']._serialized_end=211
# @@protoc_insertion_point(module_scope)
