# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from dataflow_sdk.libs.sink import sink_pb2 as v1_dot_sink_dot_sink__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in v1/sink/sink_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataHubStub(object):
    """pipeline逻辑
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoSink = channel.stream_unary(
                '/api.v1.sink.DataHub/DoSink',
                request_serializer=v1_dot_sink_dot_sink__pb2.DoSinkRequest.SerializeToString,
                response_deserializer=v1_dot_sink_dot_sink__pb2.Response.FromString,
                _registered_method=True)


class DataHubServicer(object):
    """pipeline逻辑
    """

    def DoSink(self, request_iterator, context):
        """数据入库
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataHubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoSink': grpc.stream_unary_rpc_method_handler(
                    servicer.DoSink,
                    request_deserializer=v1_dot_sink_dot_sink__pb2.DoSinkRequest.FromString,
                    response_serializer=v1_dot_sink_dot_sink__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.v1.sink.DataHub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('api.v1.sink.DataHub', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataHub(object):
    """pipeline逻辑
    """

    @staticmethod
    def DoSink(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/api.v1.sink.DataHub/DoSink',
            v1_dot_sink_dot_sink__pb2.DoSinkRequest.SerializeToString,
            v1_dot_sink_dot_sink__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
